sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@38.242.246.113 '
  # Ensure the target directory exists
  if [ -d "/var/www/myapp/repo" ]; then
    sudo rm -rf /var/www/myapp/repo
  fi

  # Clone the repository into the now empty directory
  git clone https://github.com/Saad-6/Paradise-Communications.git /var/www/myapp/repo

  # List the files to verify the clone
  echo "Listing files in /var/www/myapp/repo after cloning:"
  ls -la /var/www/myapp/repo

  # Navigate to the project directory if needed
  cd /var/www/myapp/repo

  # Check for the project file
  if [ ! -f "Paradise.csproj" ]; then
      echo "Project file not found! Listing files in the current directory:"
      ls -la
      exit 1
  fi

  # Stop the service
  sudo systemctl stop myapp.service

  # Clear the testpord directory
  sudo rm -rf /var/www/myapp/testpord/*

  # Publish the application to the target directory
  dotnet publish Paradise.csproj -c Release -o /var/www/myapp/testpord/

  # Update ownership and permissions
  sudo chown -R www-data:www-data /var/www/myapp/testpord
  sudo chmod -R 755 /var/www/myapp/testpord

  # Restart the service
  sudo systemctl daemon-reload
  sudo systemctl start myapp.service
'
