name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Ensure .NET 8 is used

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@38.242.246.113 '
          # Stop the application service to avoid conflicts
          sudo systemctl stop myapp.service

          # Ensure the repo directory exists and clear its contents
          if [ -d "/var/www/myapp/repo" ]; then
            sudo rm -rf /var/www/myapp/repo/*
          else
            sudo mkdir -p /var/www/myapp/repo
          fi

          # Clone the repository into the now-empty directory
          git clone https://github.com/Saad-6/Paradise-Communications.git /var/www/myapp/repo

          # Navigate to the directory containing the project file
          cd /var/www/myapp/repo

          # Empty the testpord directory (where the published files are located)
          if [ -d "/var/www/myapp/testpord" ]; then
            sudo rm -rf /var/www/myapp/testpord/*
          else
            sudo mkdir -p /var/www/myapp/testpord
          fi

          # Publish the application to the testpord directory, specifying the .csproj file
          dotnet publish Paradise.csproj -c Release -o /var/www/myapp/testpord/

          # Update ownership and permissions
          sudo chown -R www-data:www-data /var/www/myapp/testpord
          sudo chmod -R 755 /var/www/myapp/testpord

          # Reload the systemd manager configuration and restart the application service
          sudo systemctl daemon-reload
          sudo systemctl start myapp.service
        '
