name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Ensure .NET 8 is used

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST '
          # Clone the repository if not already cloned
          if [ ! -d "/root/myapp/repo" ]; then
            git clone https://github.com/Saad-6/Paradise-Communications.git /root/myapp/repo
          fi

          # Navigate to the repository directory
          cd /root/myapp/repo

          # Pull the latest changes from the repository
          git pull origin main

          # Publish the application to the target directory
          dotnet publish -c Release -o /root/myapp/Paradise-Prod/

          # Restart the application service
          sudo systemctl restart myapp.service
        '
