name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # This ensures that .NET 8 is used

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

    - name: Deploy to server
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@38.242.246.113 '
          cd /root/myapp/Paradise-Prod/ &&
          git pull origin main &&
          dotnet publish -c Release -o /root/myapp/Paradise-Prod/ &&
          sudo systemctl restart myapp.service
        '
